# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-10 07:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Farmer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmdata',
            name='farmer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Farmer.FarmerData'),
        ),
        migrations.AddField(
            model_name='scheduledata',
            name='farmer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Farmer.FarmerData'),
        ),
        migrations.AddField(
            model_name='scheduledata',
            name='farmer_farm',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Farmer.FarmData'),
        ),
    ]
